GET http://localhost:3005/api/persons
###
GET http://localhost:3005/info
###
GET http://localhost:3005/api/persons/3
###
DELETE http://localhost:3005/api/persons/3
###
POST http://localhost:3005/api/persons
content-type: application/json

{
    "name": "Test",
    "number": "389021380921"
}